add statistic model
turingvideo/ka-stats pull request #2
Opened 2022-05-12 15:20 UTC by lxs-turing

## Description of the change
add statistic model
// TODO Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

// TODO Fix #...

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-05-13 03:40 UTC, longshine requested changes

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +    customer_id = models.CharField(max_length=32)
Change to `org_code` to keep same as other services.

2022-05-13 03:40 UTC, longshine commented on stats/apps.py
> +    default_auto_field = 'django.db.models.BigAutoField'
This line is not needed since you've already set it in settings.py.

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +class CaseStatistics(TimedModel):
Rename to `AlertStatistic`

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +    algo_code = models.CharField(max_length=64)
Change to `event_type`

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +        db_table = 'ka_stats_case_statistics'
Remove `db_table`. Let's use the generated table name by django.

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +    eventtype_code = models.CharField(max_length=1023)
What are these two fields for? I did not see them in `ka_service`.

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +    total_read_case = models.PositiveIntegerField(default=0)
What is this field for? I did not see it in `ka_service`.

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +        ]
Ref: [unique_together](https://docs.djangoproject.com/en/4.0/ref/models/options/#unique-together)

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +        ]
Ref: https://docs.djangoproject.com/en/4.0/ref/models/options/#index-together

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +    total_box_offline = models.PositiveIntegerField(default=0)
I did not find this in ka_service. Where is it from?

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +class SiteCaseHourTrend(models.Model):
Change to `SiteAlertHourTrend`

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +    customer_id = models.CharField(max_length=32)
`org_code`

2022-05-13 03:40 UTC, longshine commented on stats/models.py
> +    total_new_case = models.PositiveIntegerField(default=0)
`total_new_alerts`

2022-05-13 04:11 UTC, lxs-turing commented on stats/models.py
> +    algo_code = models.CharField(max_length=64)
algo_code != event_type,  algo contain many eventtypes, wentao zhao bind the relationship between algo_code and event_type in ka_algo, i think event_type is the smallest statistical unit.

2022-05-13 04:14 UTC, lxs-turing commented on stats/models.py
> +    total_box_offline = models.PositiveIntegerField(default=0)
Keep naming style consistent, i modify box_count to total_box, box_offline_count to total_box_offline

2022-05-13 04:22 UTC, lxs-turing commented on stats/models.py
> +        ]
Use the [indexes](https://docs.djangoproject.com/en/4.0/ref/models/options/#django.db.models.Options.indexes) option instead.

The newer indexes option provides more functionality than index_together. index_together may be deprecated in the future.

2022-05-13 05:48 UTC, longshine commented on stats/models.py
> +        ]
Oh I see. Suggest to remove the name then. Let's use the name generated by django.

2022-05-13 05:49 UTC, longshine commented on stats/models.py
> +    algo_code = models.CharField(max_length=64)
Then why is here a `algo_code`? I did not see it in ka_service.

2022-05-13 06:14 UTC, lxs-turing commented on stats/models.py
> +    algo_code = models.CharField(max_length=64)
algo_code is not used at present, which is convenient for future use.

2022-05-14 06:57 UTC, longshine approved these changes

2022-05-14 06:57 UTC, longshine commented on stats/models.py
> +        indexes = [
unique_together

2022-05-14 06:57 UTC, longshine commented on stats/models.py
> +    site_id = models.IntegerField()
BigIntegerField

2022-05-14 07:50 UTC, longshine approved these changes

2022-05-14 07:50 UTC, merged